# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_binseg_Dr_Hocking <- function(data_vec, kmax) {
    .Call(`_Rpack2_rcpp_binseg_Dr_Hocking`, data_vec, kmax)
}

cpp_dynamic_prog <- function(input_vec, k_max) {
    .Call(`_Rpack2_cpp_dynamic_prog`, input_vec, k_max)
}

cppcumsum <- function(x) {
    .Call(`_Rpack2_cppcumsum`, x)
}

min_index <- function(arr) {
    .Call(`_Rpack2_min_index`, arr)
}

